from __future__ import annotations

import json
import logging
import tempfile
from pathlib import Path
from typing import Dict

from shared.utils import poseidon_like_hash
from services.snark_runner.snark_pipeline import BaseSnarkBackend, ProofArtifacts

logger = logging.getLogger("snark_backend.pysnark")


class PySnarkBackend(BaseSnarkBackend):  # pragma: no cover - optional path
    name = "pysnark-groth16"

    def __init__(self) -> None:
        try:
            # Import all required modules upfront
            import sys
            import pysnark
            from pysnark import options, runtime, schedule, prove
            from .snark_init import initialize_pysnark
            
            # Add pysnark to sys.modules to ensure relative imports work
            sys.modules['pysnark.options'] = options
            sys.modules['pysnark.runtime'] = runtime
            sys.modules['pysnark.schedule'] = schedule
            sys.modules['pysnark.prove'] = prove
            
            logger.info("Successfully imported all PySNARK modules")
        except ImportError as exc:  # pragma: no cover
            logger.error(f"Failed to import required modules: {exc}")
            raise RuntimeError(
                "PySNARK is not installed."
            ) from exc

        try:
            logger.info("PySNARK detected; initializing proving/verifying keys")
            initialize_pysnark("setup")  # Initialize with setup trace_id
            logger.info("Successfully initialized PySNARK")
        except Exception as e:
            logger.error(f"Failed to initialize PySNARK: {e}")
            raise

    def prove_transfer(
        self,
        sender_before: int,
        receiver_before: int,
        sender_after: int,
        receiver_after: int,
        amount: int,
        nonces: Dict[str, int],
        trace_id: str,
    ) -> ProofArtifacts:
        from .transfer_circuit import transfer_circuit
        from pysnark import prove as snark
        import json

        # Run the circuit to generate proof
        try:
            public, private, commitments = transfer_circuit(
                sender_before=sender_before,
                receiver_before=receiver_before,
                sender_after=sender_after,
                receiver_after=receiver_after,
                amount=amount,
                nonces=nonces,
            )

            # Create temporary files for proof and witness
            with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as proof_file, \
                 tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as witness_file:
                
                # Export witness data
                json.dump(private, witness_file)
                witness_file.flush()

                # Generate and export proof
                result = snark.prove()
                if result:
                    proof_data = result['proof']
                    io_data = result['io']
                else:
                    raise RuntimeError("No proof generated by PySNARK")
                
                return ProofArtifacts(
                    proof={"type": "groth16", "backend": self.name, "data": proof_data, "io": io_data},
                    public=public,
                    witness=private,
                    commitments=commitments
                )

        except Exception as e:
            logger.error(f"[{trace_id}] Proof generation failed: {e}")
            raise RuntimeError(f"Failed to generate proof: {e}") from e

